newspaper/routes/web.php
<?php

    /*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('articles', 'ArticleController');

newspaper/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'is_active', 'user_id',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

newspaper/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'is_active', 'gender',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

newspaper/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use Auth;
use App\Http\Middleware\IsActive;

class ArticleController extends Controller
{
    public $activies;

    public function __construct()
    {
        $this->middleware(['auth', IsActive::class]);
        $this->activies = ['Niektywny' => '0', 'Aktywny' => '1'];
    }

    public function index()
    {
        $articles = (new Article())->orderBy('id', 'desc')->get();

        return view('articles.index')->with('articles', $articles)->with('activies', $this->activies);
    }

    public function create()
    {
        return view('articles.create')->with('activies', $this->activies);
    }

    public function edit($id)
    {
        $articles = Article::where('id', $id)->get();

        return view('articles.edit')->with('articles', $articles)->with('activies', $this->activies);
    }

    public function store(Request $request)
    {
        $request->validate([
             'name' => ['required', 'string', 'max:191'],
            'description' => ['required', 'string', 'max:191'],
            'is_active' => ['required'],
        ]);

        $article = new Article();

        $article->name = $request->name;
        $article->description = $request->description;
        $article->updated_at = date('Y-m-d H:i:s');
        $article->created_at = date('Y-m-d H:i:s');
        $article->is_active = $request->is_active;
        $article->user_id = Auth::id();
        $article->save();

        $request->session()->flash('status', 'Dodano pomyslnie!');

        return redirect(route('articles.index'));
    }

    public function show($id)
    {
    }

    public function update(Request $request, $id)
    {
        $request->validate([
             'name' => ['required', 'string', 'max:191'],
            'description' => ['required', 'string', 'max:191'],
            'is_active' => ['required'],
        ]);

        $article = Article::where('id', $id);

        $article->update([
        'name' => $request->name,
        'description' => $request->description,
        'updated_at' => date('Y-m-d H:i:s'),
        'is_active' => $request->is_active,
        'user_id' => Auth::id(),
        ]);

        $request->session()->flash('status', 'Zapisano pomyslnie!');

        return redirect(route('articles.edit', $id));
    }

    public function destroy($id)
    {
        Article::where('id', $id)->delete();

        return redirect()->back();
    }
}

newspaper/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

newspaper/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Article;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $articles = (new Article())->with('user')->limit(5)->orderBy('id', 'desc')->get();

        return view('index')->with('articles', $articles);
    }
}

newspaper/resources/views/articles/_form.blade.php
<label>Name</label>
<input class="form-control" value="@if(Route::currentRouteName() == 'articles.edit'){{$article->name}}@endif" name="name">
<label>Desc</label>
<textarea class="form-control" name="description">@if(Route::currentRouteName() == 'articles.edit'){{$article->description}}@endif</textarea>
<label>Active</label>
<!-- {{print_r($activies)}} -->
   <select class="form-control" name="is_active">
        @foreach($activies as $key => $active)
        @if(Route::currentRouteName() == 'articles.edit')
        <option value="{{$active}}" @if($article->is_active == $active) selected="selected"  @endif>{{$key}}</option>
        @else
                <option value="{{$active}}">{{$key}}</option>

        @endif
        @endforeach

      </select>  
<div class="clearfix"></div>
<input type="submit" class="btn btn-primary" />

newspaper/resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Edycja - Artykuły</h1>
<div class="card">
      <div class="card-body">
          <form action="{{route('articles.store')}}" method="POST">
                         @if(Session::has('status'))
           <div class="alert alert-success">
           {{ Session::get('status') }}
           </div>
           @endif
                @if(count($errors->all())>0)
           <div class="alert alert-danger">
           @foreach($errors->all() as $error) 
                {{$error}}<br/>
           @endforeach
</div>
           @endif
           @csrf
          @include('articles._form')
          </form>
</div>
</div>
</div>
@endsection

newspaper/resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Edycja - Artykuły</h1>
    <div class="card">
      <div class="card-body">
           @if(Session::has('status'))
           <div class="alert alert-success">
           {{ Session::get('status') }}
           </div>
           @endif
           @if(count($errors->all())>0)
           <div class="alert alert-danger">
           @foreach($errors->all() as $error) 
                {{$error}}
           @endforeach
</div>
           @endif
          @foreach($articles as $article)
          <form action="{{route('articles.update',['id'=>$article->id])}}" method="POST">
            @method('patch')
           @csrf
          
@include('articles._form')

</form>
@endforeach
</div>
</div>
</div>
@endsection

newspaper/resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Artykuły <a href="{{route('articles.create')}}" class="btn btn-success">Nowy</a></h1>
    
     
    <table class="table table-striped">
        <thead class="thead-white">
            <tr>
            <th scope="col">
                #
            </th>
            <th scope="col">
            name
            </th>
            <th scope="col">
                desc
</th>
            <th scope="col">
     is_active
</th>
            <th scope="col">
                options
            </th>
            </tr>
        </thead>
        <tbody>
        @foreach($articles as $key => $article) 
    <tr>
        <td>
{{(int)$key+1}}
        </td>
        <td>
{{$article->name}}
        </td>
        <td>
{{$article->description}}
        </td>
        <td>
            {{$article->is_active}}
        </td>
        <td>
            <a class="btn btn-link" href="{{route('articles.edit',['id'=>$article->id])}}">
                edytuj
            </a>

                   <form action="{{route('articles.destroy',['id'=>$article->id])}}" method="POST">
            @method('delete')
           @csrf
          
<input type="submit" value="usuń" class="btn btn-link" />

</form>
        </td>
    </tr>
        @endforeach
        </tbody>
    </table>
</div>

@endsection

newspaper/resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
        @foreach($articles as $article)
        @if($article->is_active == '1')
            <div class="card">
                <div class="card-header"><h3 class="card-title">{{$article->name}}</h3></div>
                <div class="card-body">
   
                {{$article->description}}
                </div>
                <div class="card-footer text-muted">
    Utworzono: {{$article->created_at}} przez {{$article['user']->first_name}}
  </div>
            </div>
            @endif
            @endforeach
        </div>
    </div>
</div>
@endsection

newspaper/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Zadanie 1') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Zadanie 1
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('articles.index') }}">Zarządzaj artykułami</a>
                        </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->first_name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>